# Generated by Django 3.2 on 2021-11-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('genre', models.CharField(choices=[(1, 'Comedy'), (2, 'Sci-fi'), (3, 'Horror'), (4, 'Romance'), (5, 'Action'), (6, 'Thriller'), (7, 'Drama'), (8, 'Mystery'), (9, 'Crime'), (10, 'Animation'), (11, 'Adventure'), (12, 'Fantasy')], max_length=50)),
                ('release_date', models.DateField()),
                ('up_votes', models.PositiveSmallIntegerField(default=0)),
                ('down_votes', models.SmallIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('reviews', models.ManyToManyField(default='', to='movies.MovieReview')),
            ],
            options={
                'ordering': ['up_votes', 'down_votes', 'release_date'],
            },
        ),
    ]
