# Generated by Django 3.2 on 2021-11-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-up_votes', '-down_votes', '-release_date']},
        ),
        migrations.AddField(
            model_name='movies',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
